version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - HTTP_PORT=80
      - SOCKET_PORT=81
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "81:81"
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver : bridge